# Config for the right index finger1
[Fingers]

[[motors]]
finger_name = "r_finger1"

[motors.motor1]
id = 1
offset = -1.5697736729363063
invert = false
model = "SCS0009"

[motors.motor2]
id = 2
offset = 1.4419419406125027
invert = false
model = "SCS0009"

[[motors]]
finger_name = "r_finger2"

[motors.motor1]
id = 3
offset = -1.5697736729363063
invert = false
model = "SCS0009"

[motors.motor2]
id = 4
offset = 1.4419419406125027
invert = false
model = "SCS0009"

[[motors]]
finger_name = "r_finger3"

[motors.motor1]
id = 5
offset = -1.5544338650574498
invert = false
model = "SCS0009"

[motors.motor2]
id = 6
offset = 1.416375594147742
invert = false
model = "SCS0009"

[[motors]]
finger_name = "r_finger4"

[motors.motor1]
id = 7
offset = -1.5493205957644978
invert = false
model = "SCS0009"

[motors.motor2]
id = 8
offset = 1.4214888634406941
invert = false
model = "SCS0009"
